# Generated by Django 2.1.7 on 2019-03-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('profile', models.ImageField(upload_to='')),
                ('education_level', models.CharField(choices=[('SLC', 'S.L.C'), ('+2', '+2'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=200)),
                ('work_experience', models.TextField(choices=[('6 months', '6 months'), ('1 year', '1 year'), ('2 years or more', '2 years or more')], max_length=200)),
            ],
        ),
    ]
